### ISSUE TITLE
Support keyboard input

### ISSUE THREAD

**Issue by chamoda** [chamoda/react-calculator#11]
Add support for keyboard input for numbers and symbols

**Comment by 1337-ishaan** [comment]
https://github.com/1337-ishaan/calculator-react

Check my repo, it has supported keyboard input, star it if you like it ;)

**Comment by devchamoda** [comment]
@1337-ishaan Nice 👍 

You are welcome to create a PR here.

**Comment by chamoda** [comment]
@1337-ishaan Nice 👍

You are welcome to create a PR here.
